plugins { id 'com.android.application' }

android {
    namespace 'ke.co.dasify.dasfund'
    compileSdk 35

    defaultConfig {
        applicationId 'ke.co.dasify.dasfund'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
